### ISSUE TITLE
Use `localhost` in the demo

### ISSUE THREAD

**Issue by freewind** [Centaur/repox#14]
In the example code of [wiki](https://github.com/Centaur/repox/wiki/%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97), it uses `192.168.0.120` for demo, why not just use `localhost`? 

It cost me an hour to find out why repox is not working, at last I found the IP is hardcoded

```
[repositories]
local
repox-maven: http://192.168.0.120:8078/
repox-ivy: http://192.168.0.120:8078/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

**Comment by Centaur** [comment]
![文档里有提到](http://d.pcs.baidu.com/thumbnail/7df77f624823bc07be33c97472d3a950?fid=3089688422-250528-935116169411885&time=1427018400&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-pHDxpOgzaW6zILlCCDdleUzxHMQ%3d&expires=8h&prisign=unknow&chkbd=0&chkv=0&size=c2560_u1440&quality=90)

**Comment by freewind** [comment]
我看到这个了，但是在copy的时候忘了，为什么不能提供一个直接copy就能用的？

**Comment by Centaur** [comment]
最推荐的部署方式不是在本机，而是公司私服。
