### ISSUE TITLE
访问无响应

### ISSUE THREAD

**Issue by hauter** [Centaur/repox#35]
编译 ok, 运行 ok, 也没什么错误 。
但访问 http://localhost:8078/ 没什么响应。
netstat -na | grep LISTEN 显示有程序在监听 8078

**Comment by Centaur** [comment]
repox 的本质是一个代理缓存，而不是一个镜像，并不支持显示资源列表。当前版本中访问 `/` 会 404，在新版本中会重定向至社区公服介绍的页面。按照 wiki 中的方式正确配置sbt后可正常使用。

**Comment by hauter** [comment]
今天我试了一下。原因是，我开了 shadowsocks , 于是 localhost 就访问不了了。谢谢
