### ISSUE TITLE
关于repo清单的问题

### ISSUE THREAD

**Issue by jaohaohsuan** [Centaur/repox#36]
为何[http://repo.typesafe.com/typesafe/ivy-releases/](http://repo.typesafe.com/typesafe/ivy-releases/)不在默认清单内呢?

**Comment by Centaur** [comment]
清单中的 http://dl.bintray.com/typesafe/ivy-releases/ 就是这个，你可以把上面的链接贴到浏览器里连一下试试。

**Comment by jaohaohsuan** [comment]
我原以为是安装好就在默认的清单内, 原来要把这个`repox/src/main/resources/admin/repox.config.json`档案做import.

你的项目很好的结局了我的问题, 谢谢你
