### ISSUE TITLE
本地配置使用 repox 不成功

### ISSUE THREAD

**Issue by loveyanbei** [Centaur/repox#37]
rt，如果repositories只保留repox，所有的上游都返回404，不管我把超时调到多久（120+秒）重试20+次，sbt秒报错
查看日志有大量的404，其中包括osc，检查发现有的404根本不是真正的404，然而我把延时调到很长时间为什么不能起作用呢？
[info] Loading project definition from /home/hadooptest/installer/spark-jobserver/project
[info] Updating {file:/home/hadooptest/installer/spark-jobserver/project/}spark-jobserver-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalariform#scalariform_2.10;0.1.4: several problems occurred while resolving dependency: org.scalariform#scalariform_2.10;0.1.4 {compile=[default(compile)]}:
[warn] 	URI has an authority component
[warn] 	URI has an authority component
[warn] 	:: org.scalactic#scalactic_2.10;2.2.1: several problems occurred while resolving dependency: org.scalactic#scalactic_2.10;2.2.1 {compile=[default(compile)]}:
[warn] 	URI has an authority component
[warn] 	URI has an authority component
[warn] 	:: org.pantsbuild#jarjar;1.6.0: several problems occurred while resolving dependency: org.pantsbuild#jarjar;1.6.0 {compile=[default(compile)]}:
[warn] 	URI has an authority component
[warn] 	URI has an authority component
[warn] 	:: org.scalastyle#scalastyle-sbt-plugin;0.8.0: several problems occurred while resolving dependency: org.scalastyle#scalastyle-sbt-plugin;0.8.0 {compile=[default(compile)]}:
[warn] 	URI has an authority component
[warn] 	URI has an authority component

**Comment by loveyanbei** [comment]
配置用了公服的，超时等待设置了30-120s，很长了

**Comment by loveyanbei** [comment]
head retry的次数改成了30s/100000刺，所有的连接器超时30秒，还是秒失败，这不是逗我么。。。

**Comment by notyy** [comment]
你直接到群里问吧。。。

**Comment by loveyanbei** [comment]
@notyy 刚才在日本的vps上面部署，依然用不了0 0，到哪个群？

**Comment by Centaur** [comment]
请将 ~/.sbt/repositories 文件及 ~/.repox/repox.log 发上来。

日志里的 404 不是问题。repox的做法是同时给多个上游发请求，很多 artifact 只在某一两个仓库中有，自然其它的都会404.

另外你说的“配置了公服”，是指社区公服吗？你应该是没有权限设置公服的超时参数的。

**Comment by loveyanbei** [comment]
@Centaur 不，是用公服的设置丢到了vps，改了一下几个中央库的优先级，全部丢到了第一优先级就能用了，另外手动把scala-lang和scala-plugin也加上，这样去编译spark-jobserver就没有resolve问题了。我觉得，你们应该把所有的库地址放在一个优先级里面，分开了反而会出些乱糟糟的事情。

**Comment by loveyanbei** [comment]
@Centaur 之前是国外的中央库不在第一优先，而第一组的oschina这几天又爆炸了，全程504

**Comment by Centaur** [comment]
因为没有看到你的配置文件，所以无法判断是哪里出了问题。很高兴你的问题已经解决，这个issue关掉了。
