### ISSUE TITLE
执行 sbt assembly 也会下载大量 jar 包，怎么办？ 

### ISSUE THREAD

**Issue by wangyufeng0615** [Centaur/repox#45]
下载了很多 jar 包，而且最后还 download failed 了。

`[error] (*:update) sbt.ResolveException: download failed: com.typesafe.akka#akka-stream_2.11;2.4.3!akka-stream_2.11.jar`

这些 jar 包能从别的途径下载吗？

**Comment by Centaur** [comment]
assembly 之间当然要先编译，编译当然要下载依赖。

**Comment by kidsbmilk** [comment]
https://cwiki.apache.org/confluence/display/SPARK/Useful+Developer+Tools#UsefulDeveloperTools-ReducingBuildTimes
可以试试：build/sbt clean package
