### ISSUE TITLE
twttr上的包下载不了

### ISSUE THREAD

**Issue by kidsbmilk** [Centaur/repox#50]
[error] Server access Error: 连接超时 url=http://maven.twttr.com/org/apache/httpcomponents/httpcomponents-client/4.3.2/httpcomponents-client-4.3.2.jar
[info] Resolving org.apache.httpcomponents#project;7 ...
[error] Server access Error: 连接超时 url=http://maven.twttr.com/org/apache/httpcomponents/httpcomponents-core/4.3.1/httpcomponents-core-4.3.1.jar

**Comment by Centaur** [comment]
访问 maven.twttr.com 需要翻墙，请阅读[此文档](https://github.com/Centaur/repox/wiki/%E9%85%8D%E7%BD%AE%E4%BB%A3%E7%90%86) 设置代理。

**Comment by kidsbmilk** [comment]
我已经用shadowsocks翻墙了，不行，晚上试试lantern再来回复，谢谢~

**Comment by Centaur** [comment]
仅支持 http/https 代理

**Comment by kidsbmilk** [comment]
我那个shadowsocks设置的是全局代理，那么repox应该也能翻墙的吧

**Comment by kidsbmilk** [comment]
还是不行，下载不了，Server access Error: 连接超时
