### ISSUE TITLE
-Dsbt.override.build.repos=true  覆盖掉了自定义的resolvers

### ISSUE THREAD

**Issue by hujianxin** [Centaur/repox#52]
项目现在用到一个第三方的库地址。所以需要在build.sbt里面添加resolvers，但是加上-Dsbt.override.build.repos=true之后，就不行了。这个怎么办呢？

**Comment by Centaur** [comment]
1. 修改 ~/.sbt/repositories，把你的 resolver 加在里面
2. 临时把 -Dsbt.override.build.repos 改为 false，等这个库下载完了再改回来
没有一劳永逸的办法。

**Comment by hujianxin** [comment]
多谢多谢。
