### ISSUE TITLE
使用了coursier后，链接repo会出现这个错误

### ISSUE THREAD

**Issue by TopSpoofer** [Centaur/repox#55]
使用了coursier后，链接repo会出现这个错误。但如果用coursier直接链接上游服务不会出错！在浏览器中访问 http://localhost:8078/org/webjars/debug/0.7.4/debug-0.7.4.jar 是可以成功下载的，不知道原因！

```
[info] Fetched artifacts of hebee-build
coursier.ResolutionException: 6 not found
  http://localhost:8078/org/webjars/debug/0.7.4/debug-0.7.4.jar
  http://localhost:8078/org/webjars/diff/1.0.7/diff-1.0.7.jar
  http://localhost:8078/org/webjars/jshint-node/2.4.1-1/jshint-node-2.4.1-1.jar
  http://localhost:8078/org/webjars/less-node/1.6.0-1/less-node-1.6.0-1.jar
  http://localhost:8078/org/webjars/mocha/1.17.1/mocha-1.17.1.jar
  http://localhost:8078/org/webjars/rjs/2.1.11-1-trireme/rjs-2.1.11-1-trireme.jar
[error] (*:update) coursier.ResolutionException: 6 not found
[error]   http://localhost:8078/org/webjars/debug/0.7.4/debug-0.7.4.jar
[error]   http://localhost:8078/org/webjars/diff/1.0.7/diff-1.0.7.jar
[error]   http://localhost:8078/org/webjars/jshint-node/2.4.1-1/jshint-node-2.4.1-1.jar
[error]   http://localhost:8078/org/webjars/less-node/1.6.0-1/less-node-1.6.0-1.jar
[error]   http://localhost:8078/org/webjars/mocha/1.17.1/mocha-1.17.1.jar
[error]   http://localhost:8078/org/webjars/rjs/2.1.11-1-trireme/rjs-2.1.11-1-trireme.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by Centaur** [comment]
感谢提交，已确认是 repox 的bug。

**Comment by TopSpoofer** [comment]
@Centaur 问题定位到了么？我也在看源码学习中！！！！

**Comment by Centaur** [comment]
@TopSpoofer  应该是 sha1 checksum 下载导致的问题。sbt 对任何一个 artifact ，都是先下载 .pom/.ivy/.jar ，然后下载 .pom.sha1/.ivy.sha1/.jar.sha1 ，来自不同仓库的同一个 artifact ，可能有不同的 .sha1 值（因为有些仓库会自己从源码重新打包）。为保证 .sha1 与 artifact 的对应关系，repox 目前强制 .sha1 必须从相应的 artifact 来源的 upstream 下载。

但是 Coursier 的下载是并发的（这也是 Coursier 的优势之一），因此对 x.jar ，或能会先发起 x.jar.sha1 的下载请求，然后才发起x.jar的请求，这时就会导致 x.jar 来源 upstream 与 x.jar.sha1 的来源 upstream  不同，从而导致 checksum 失败。

所以这个问题只在使用 Coursier 时存在，当发生这个问题时，一个不那么方便的解决办法是到 ~/.coursier/ 目录下将出错的 artifact 及其 .sha1 checksum 文件删除，重新下载。目前 repox 的实现能够保证 repox 缓存中的状态是正确的。通常重新下载能够保证文件来源的一致性。

也因为 repox 实现时没有考虑到出现基于 Coursier 的客户端的情况，所以这个bug的修正可能会涉及比较大的代码改动，需要耐心等待。因此在修正之前不再建议使用 Coursier ，还是使用原生 sbt 比较稳妥。

**Comment by darkjh** [comment]
https://github.com/alexarchambault/coursier/blob/5b2237a194226e2ba3cae71928e4e810701ee632/cache/src/main/scala/coursier/Cache.scala#L863
Checksum的url是从`Artifact`对象里面来的，所以一个sha1总是和artifact从同一个源里面拿取的。

**Comment by Centaur** [comment]
@darkjh 对于 coursier来说，repox是它唯一的源.

**Comment by bash-horatio** [comment]
这么说和 #63 矛盾……要么卡在#63的问题，要么卡类似not found的问题……

**Comment by TopSpoofer** [comment]
@bash-horatio 现在没有用这个了

**Comment by Centaur** [comment]
@bash-horatio #63 是 repox server 编译期的问题，本问题是 sbt 运行期的问题，如果你要搭建repox私服，只需要用 #63 的workround把依赖下载好，编译完能打出包就可以跑了。在后续使用时 sbt 不使用 coursier就可以workround本问题。

**Comment by Centaur** [comment]
With the fix of #63, I will close this issue. All you have to do is 

1. Stop using cousier
2. Checkout the latest code
