### ISSUE TITLE
sbt assembly 打包 报错

### ISSUE THREAD

**Issue by adonis2014** [Centaur/repox#56]
[error] Server access Error: 没有到主机的路由 url=http://repo.caimi-inc.com/nexus/content/groups/public/com/eed3si9n/sbt-assembly_2.10_0.13/0.14.1/sbt-assembly-0.14.1.pom
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
[error] Server access Error: 没有到主机的路由 url=http://repo.caimi-inc.com/nexus/content/groups/public/org/scala-lang/scala-compiler/2.10.4/scala-compiler-2.10.4.pom
[info] Resolving jline#jline;2.11 ...
[error] Server access Error: 没有到主机的路由 url=http://repo.caimi-inc.com/nexus/content/groups/public/jline/jline/2.11/jline-2.11.pom
[info] Resolving com.jcraft#jsch;0.1.46 ...
[error] Server access Error: 没有到主机的路由 url=http://repo.caimi-inc.com/nexus/content/groups/public/com/jcraft/jsch/0.1.46/jsch-0.1.46.pom
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[error] Server access Error: 没有到主机的路由 url=http://repo.caimi-inc.com/nexus/content/groups/public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.6 ...
[warn] 	[FAILED     ] org.scala-lang#scala-library;2.10.4!scala-library.jar: URI has an authority component (0ms)
[error] Server access Error: 没有到主机的路由 url=http://repo.caimi-inc.com/nexus/content/groups/public/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
[warn] 	[FAILED     ] org.scala-lang#scala-library;2.10.4!scala-library.jar:  (0ms)
[warn] ==== local: tried
[warn]   /root/.ivy2/local/org.scala-lang/scala-library/2.10.4/jars/scala-library.jar
[warn] ==== maven-local: tried
[warn]   file://~/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-library/2.10.4/jars/scala-library.jar
[warn] ==== community-plugins-ivy-releases: tried
[warn]   https://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-lang/scala-library/2.10.4/jars/scala-library.jar
[warn] ==== maven-repo-caimi: tried
[warn]   http://repo.caimi-inc.com/nexus/content/groups/public/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.14.1: URI has an authority component
[warn] 	:: org.scala-lang#scala-compiler;2.10.4: URI has an authority component
[warn] 	:: jline#jline;2.11: URI has an authority component
[warn] 	:: com.jcraft#jsch;0.1.46: URI has an authority component
[warn] 	:: org.scala-sbt#test-interface;1.0: URI has an authority component

**Comment by Centaur** [comment]
@adonis2014 "没有到主机的路由" 是你本地与目标服务器的网络有问题。 `URI has an authority component` 的意思是这个仓库需要用户名密码才能访问。先连公服试试吧。

**Comment by adonis2014** [comment]
好的，谢谢。 
另外 问下 repox 必须得 在scala 2.11 下编译是哪

**Comment by Centaur** [comment]
2.11 出来好几年了，所以现在的代码我还真没在 2.10 上编过。就用 2.11 吧，马上 2.12 就要出来了。
