### ISSUE TITLE
repox部署完后可以用，但管理界面有问题

### ISSUE THREAD

**Issue by yanhaijian** [Centaur/repox#57]
repox部署完后可以用，但管理界面有问题，不知道是不配置有问题，代码是下载的最新版，截图如下：
![image](https://cloud.githubusercontent.com/assets/1964226/19679102/2923cdc6-9ad3-11e6-8357-fd8eda8eb32c.png)

**Comment by Centaur** [comment]
请确认严格按照 [文档](https://github.com/Centaur/repox/wiki/%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97) 描述的过程编译部署。

有一个小问题是 semantic-ui 的 css 引用了被墙的 google web font，会导致页面加载缓慢。为了保证流畅访问页面，你有两个选择：

1. 翻墙
2. 手动修改 `bower_components/semantic-ui/dist/semantic-ui.min.css` 将第一个分号之前对 google web font 的引用删除，然后重新打包。
