### ISSUE TITLE
repo清单中能否增加cloudera的仓库，以及gradle plugins的仓库？

### ISSUE THREAD

**Issue by cycorey** [Centaur/repox#60]
https://repository.cloudera.com/artifactory/cloudera-repos/
https://plugins.gradle.org/m2/

谢谢！

**Comment by Centaur** [comment]
cloudera-repos 已经有了，优先级 3
gradle plugins 仓库已添加，优先级 7

可以从 [此处](http://repox.gtan.com:8078/admin/exportConfig) 下载最新的公服配置。
