### ISSUE TITLE
使用sbt 编译报错

### ISSUE THREAD

**Issue by oaksharks** [Centaur/repox#61]
[info] Compiling 49 Scala sources to /data/linux/repox-master/target/scala-2.11/classes...
[error] missing or invalid dependency detected while loading class file 'DefaultReads.class'.
[error] Could not access type Instant in value java.time,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'DefaultReads.class' was compiled against an incompatible version of java.time.
[error] missing or invalid dependency detected while loading class file 'DefaultReads.class'.
[error] Could not access type LocalDate in value java.time,

**Comment by Centaur** [comment]
repox 需要 java 8.  java.time 这个包是 java 8 里的。
