### ISSUE TITLE
我本来就是连不上sbt，结果你的repox自己要sbt assembly

### ISSUE THREAD

**Issue by luyang177** [Centaur/repox#66]
明白了，可以用公网，太感谢了

-------------------------------------------------------------------------------------------------

我本来就是连不上sbt，结果你的repox自己要sbt assembly
然后自然就下不下来了，这不是死循环么？

你的‘入门指南’提到

    $ git clone https://github.com/Centaur/repox.git
    $ cd repox/src/main/resources/admin
    $ bower install
    $ cd ../../../..
    $ sbt assembly

**Comment by Centaur** [comment]
看来问题已经解决了。
