### ISSUE TITLE
All my browser stalls but didn't load admin page

### ISSUE THREAD

**Issue by zhongwm** [Centaur/repox#67]
All my browser stalls but didn't load page http://10.10.8.57:8078/admin/admin.html
http timing says stalled not finished yet. but page didn't show.

server environment: centos6 openjdk1.8

**Comment by zhongwm** [comment]
Same for Oracle jdk1.8_u111 on mac os x 10.12.

**Comment by Centaur** [comment]
1. Make sure you run `bower install`  before assembly.
2. SemanticUI's css uses google font which is GFWed. You can manually edit `src/resources/admin/bower_components/semantic-ui/dist/semantic.css` , delete the first line `@import 'https"//fonts.googleapis.com/css....`, then run `sbt assembly`.

**Comment by zhongwm** [comment]
1. Actually I have did ```bower install``` befoer ```sbt assembly```
2. As for the GFWed part, I do have my browser proxied, so it shouldn't be a problem.

At the beginning I thought that was a problem of Chrome, considering Chrome often stalls sometimes on some very popular sites. but my repox instance, it constantly occurs on firefox, Safari, and even non-proxied Internet Explorer.
