### ISSUE TITLE
现阶段repox 支持sbt 1.2.x吗？

### ISSUE THREAD

**Issue by TopSpoofer** [Centaur/repox#85]
现阶段repox 支持sbt 1.2.x吗？

**Comment by Centaur** [comment]
试了一下，目前master上的最后版本支持sbt `1.2.8`没有问题。
但是请注意，从`1.3.0`版本开始，sbt默认使用`Coursier`进行依赖管理，它所使用的并发请求方式repox 是从原理上不支持的，如果要使用sbt 1.3.0，需要在项目`build.sbt`中指定 `ThisBuild / useCoursier := false` 以获得与`1.2.x`相同的结果。参考 https://www.lightbend.com/blog/sbt-1.3.0-release

**Comment by Centaur** [comment]
FYI, 根据 https://github.com/sbt/sbt/issues/4878 ，如果你使用sbt 1.3.0，而且在 `project/plugins.sbt` 中使用了插件的话，需要在 `project/plugins.sbt`　中添加 `useCoursier := false`　才能与 repox 合作.
